title: Just some notes...
author: Kahlil (Kal) Hodgson
email: kahlil.hodgson999@gmail.com
description: >-
  Adventures in technology, linux, fedora, devops, virtualization, programming,
  maths, logic, data science, machine learning, music theory, and other random
  stuff.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: tartansandal

# Build settings
markdown: kramdown
kramdown:
  input: GFM

discus:
  shortname: tartansandal

theme: minima
plugins:
  - jekyll-feed

# Theme settings
minima:
  date_format: "%-d %B %Y"

header_pages: []
  - about.md

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - TODO.md
