title: Just some notes...
author: Kahlil (Kal) Hodgson
email: kahlil.hodgson999@gmail.com
description: >-
  Adventures in technology, linux, fedora, devops, virtualization, programming,
  maths, logic, data science, machine learning, music theory, and other random
  stuff.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tartansandal.github.io"  # needed for Disqus
github_username: tartansandal

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Theme settings
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: tartansandal

minima:
  date_format: "%-d %B %Y"

header_pages:
  - about.md

show_excerpts: true

# Paths excluded from processing
exclude:
  # default excusions
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # extra exclusions
  #- .bundle
  - README.md
  - Makefile
